### ISSUE TITLE
TS3 Source

### ISSUE THREAD

**Issue by MakerTim** [adocilesloth/TS3OBSPlugin#1]
Is the TS3 plugin also opensource?
If so, it may be easyer to add that kind of stuff in the readme.md, 
also a download link for the obs plugin in the readme is recommended to do.

**Comment by adocilesloth** [comment]
This plugin you see here is open source. It uses the Client Query plugin in TS3 which I did not write. You would have to find the author of that plugin to determine if it's open source or not.

It's a plugin for OBS, as such, the download links are available on the OBS forum: https://obsproject.com/forum/threads/teamspeak-3-plugin.12628/

If someone is here looking at the code, I assumed that they would have come via the above link and as such have access to the downloads anyway. Or they could download and compile the plugin themselves.
